# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSR8pHndI45LLSIm0pItcaTPCyAfgZeM
"""

!pip install scipy matplotlib gtts

from google.colab import files

uploaded = files.upload()

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):
    sample_rate, data = wavfile.read(wav_file)

    if len(data.shape) > 1:
        data = data[:, 0]

    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')
    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.grid(True)
    plt.show()

wav_file = 'pianos-by-jtwayne-7-174717.wav'

from gtts import gTTS
import os

text = "Hi everyone how are you"

language = 'en'
tts = gTTS(text=text, lang=language, slow=False)

audio_file = "output.mp3"
tts.save(audio_file)

from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = "Hi mister Stark"
language = 'en'
tts = gTTS(text=text, lang=language, slow=False)
audio_file = "output.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)